security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        user:
            entity: { class: App\Entity\User , property: email }
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 15
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            stateless: true
            anonymous: true
            provider: user
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true
            

            json_login:
                
                check_path: /login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            


    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/users/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/users/, roles: IS_AUTHENTICATED_FULLY }
            - { path: ^/api/annonces/, roles: IS_AUTHENTICATED_FULLY }

        
  
            
        
    
        
        
        
        



        

   



            






        
